name: Update Now Playing

on:
  schedule:
    - cron: "*/3 * * * *"

  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install @supabase/supabase-js

      - name: Run updater
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URI }}
          SUPABASE_ANON_KEY: ${{ secrets.SUPABASE_KEY }}
        run: node .github/scripts/update-readme.js

      - name: Commit changes
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

          git add README.md

          git diff --cached --quiet || git commit -m "Update now playing"

          git push
